apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: postgres-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100M
  hostPath:
    path: /data
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  storageClassName: manual
